In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('iris.csv')

In [4]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [5]:
df = df.iloc[:,1:]

In [6]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
X = df.iloc[:,:4]

In [8]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [10]:
y = df.iloc[:,4]

In [11]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
lr = LabelEncoder()

In [28]:
y = lr.fit_transform(y)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state =22)

In [30]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 2, 2, 1, 1, 0, 0, 1, 1, 2, 2, 0, 1, 1, 2,
       0, 0, 0, 0, 0, 0, 2, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 2, 2, 0, 2, 0, 2,
       0, 1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 1, 0, 1, 0,
       2, 2, 2, 2, 0, 2, 2, 0, 1, 1, 0, 2, 0, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       1, 0, 0, 2, 1, 2, 2, 0, 2, 2])

In [31]:
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
30             4.8           3.1            1.6           0.2
31             5.4           3.4            1.5           0.4
89             5.5           2.5            4.0           1.3
90             5.5           2.6            4.4           1.2
55             5.7           2.8            4.5           1.3
..             ...           ...            ...           ...
102            7.1           3.0            5.9           2.1
100            6.3           3.3            6.0           2.5
44             5.1           3.8            1.9           0.4
132            6.4           2.8            5.6           2.2
117            7.7           3.8            6.7           2.2

[120 rows x 4 columns]

In [64]:
weights = np.zeros((5,))

In [55]:
weights

array([0., 0., 0., 0., 0.])

In [34]:
ones = np.ones((120))

In [35]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [36]:
X_new = np.c_[ones,X_train]

In [37]:
X_new

array([[1. , 4.8, 3.1, 1.6, 0.2],
       [1. , 5.4, 3.4, 1.5, 0.4],
       [1. , 5.5, 2.5, 4. , 1.3],
       [1. , 5.5, 2.6, 4.4, 1.2],
       [1. , 5.7, 2.8, 4.5, 1.3],
       [1. , 5. , 3.4, 1.6, 0.4],
       [1. , 5.1, 3.4, 1.5, 0.2],
       [1. , 4.9, 3.1, 1.5, 0.1],
       [1. , 6.9, 3.1, 5.4, 2.1],
       [1. , 6.7, 2.5, 5.8, 1.8],
       [1. , 7. , 3.2, 4.7, 1.4],
       [1. , 6.3, 3.3, 4.7, 1.6],
       [1. , 5.4, 3.9, 1.3, 0.4],
       [1. , 4.4, 3.2, 1.3, 0.2],
       [1. , 6.7, 3. , 5. , 1.7],
       [1. , 5.6, 3. , 4.1, 1.3],
       [1. , 5.7, 2.5, 5. , 2. ],
       [1. , 6.5, 3. , 5.8, 2.2],
       [1. , 5. , 3.6, 1.4, 0.2],
       [1. , 6.1, 2.8, 4. , 1.3],
       [1. , 6. , 3.4, 4.5, 1.6],
       [1. , 6.7, 3. , 5.2, 2.3],
       [1. , 5.7, 4.4, 1.5, 0.4],
       [1. , 5.4, 3.4, 1.7, 0.2],
       [1. , 5. , 3.5, 1.3, 0.3],
       [1. , 4.8, 3. , 1.4, 0.1],
       [1. , 5.5, 4.2, 1.4, 0.2],
       [1. , 4.6, 3.6, 1. , 0.2],
       [1. , 7.2, 3.2, 6. , 1.8],
       [1. , 5

In [38]:
X_new.shape

(120, 5)

In [63]:
iter = 300
alpha = 0.001

In [40]:
from numpy import exp

In [65]:
for i in range(iter):
    z = np.dot(X_new,weights)
    p = 1/(1+exp(-z))
    weights = weights - alpha*np.dot(X_new.T,(p-y_train))

In [66]:
weights

array([ -2.32425811,   5.34472043, -12.81480634,  41.28512092,
        18.91399227])

In [67]:
X_test.shape

(30, 4)

In [68]:
ones_1 = np.ones((30,))

In [70]:
ones_1.shape

(30,)

In [71]:
X_pred = np.c_[ones_1,X_test]

In [72]:
X_pred

array([[1. , 5.4, 3.7, 1.5, 0.2],
       [1. , 6.4, 3.2, 5.3, 2.3],
       [1. , 6.5, 2.8, 4.6, 1.5],
       [1. , 6.3, 2.5, 5. , 1.9],
       [1. , 6.1, 2.9, 4.7, 1.4],
       [1. , 6.8, 2.8, 4.8, 1.4],
       [1. , 6.7, 3.1, 4.7, 1.5],
       [1. , 6. , 3. , 4.8, 1.8],
       [1. , 5.6, 2.9, 3.6, 1.3],
       [1. , 5. , 3.2, 1.2, 0.2],
       [1. , 6.9, 3.2, 5.7, 2.3],
       [1. , 5.7, 3. , 4.2, 1.2],
       [1. , 7.4, 2.8, 6.1, 1.9],
       [1. , 7.2, 3.6, 6.1, 2.5],
       [1. , 5. , 3.5, 1.6, 0.6],
       [1. , 7.9, 3.8, 6.4, 2. ],
       [1. , 5.6, 2.5, 3.9, 1.1],
       [1. , 5.7, 2.8, 4.1, 1.3],
       [1. , 6. , 2.2, 5. , 1.5],
       [1. , 5.7, 2.9, 4.2, 1.3],
       [1. , 5.1, 3.8, 1.6, 0.2],
       [1. , 6.9, 3.1, 5.1, 2.3],
       [1. , 5.5, 3.5, 1.3, 0.2],
       [1. , 5.8, 2.6, 4. , 1.2],
       [1. , 5.8, 2.7, 5.1, 1.9],
       [1. , 4.7, 3.2, 1.3, 0.2],
       [1. , 7.2, 3. , 5.8, 1.6],
       [1. , 6.5, 3. , 5.2, 2. ],
       [1. , 6.7, 3.3, 5.7, 2.1],
       [1. , 6

In [73]:
X_pred.shape

(30, 5)

In [74]:
y_pred = np.dot(X_pred,weights)

In [75]:
y_pred

array([ 44.8329286 , 253.18789548, 214.8175116 , 241.67265469,
       213.63525566, 222.78655268, 216.17052587, 223.51341198,
       163.6578632 ,  36.71690732, 272.37430407, 185.79052793,
       289.12103828, 289.14864448,  56.9521107 , 293.25552766,
       177.38652356, 186.11637634, 236.34808355, 188.96340779,
        46.07654393, 248.88471214,  39.67333773, 183.19389833,
       240.5658453 ,  39.24200329, 267.42939896, 246.48261902,
       266.24108089, 227.14531733])

In [76]:
y_pred.shape

(30,)

In [77]:
y_pred1 = []
for i in y_pred:
    if i < 0.5:
        y_pred1.append(0)
    else:
        y_pred1.append(1)

In [78]:
y_pred1

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [79]:
from sklearn.metrics import accuracy_score

In [80]:
accuracy_score(y_test,y_pred1)

0.3333333333333333

In [81]:
# No it does not provide better results than report in Q4